version: '3'

services:
    article_splicing:
       build:
         context: .
         dockerfile: Dockerfile
       volumes:
         - ./:/app
       stdin_open: true
       tty: true
       entrypoint: ["python", "/app/run.py"]
